<script setup>
import { ref, onMounted } from 'vue';
import { usePage } from '@inertiajs/vue3';
import AppLayout from '@/Layouts/AppLayout.vue';


const { props } = usePage();

console.log('props', props)
const records = ref(props.records);


</script>

<template>
    <AppLayout title="Barcode Records">
        <div class="max-w-7xl mx-auto flex flex-col gap-3 px-4 sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <div class="flex flex-col">
                        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                                <div
                                    class="shadow overflow-hidden border-b border-gray-200 dark:border-gray-700 sm:rounded-lg">
                                    <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                        <thead class="bg-gray-50 dark:bg-gray-800">
                                            <tr>
                                                <th scope="col"
                                                    class="px-6 py-3 text-left text-xs font-bold text-black dark:text-gray-400 uppercase tracking-wider">
                                                    Record Id
                                                </th>
                                                <th scope="col"
                                                    class="px-6 py-3 text-left text-xs font-bold text-black dark:text-gray-400 uppercase tracking-wider">
                                                    Client Name
                                                </th>
                                                <th scope="col"
                                                    class="px-6 py-3 text-left text-xs font-bold text-black dark:text-gray-400 uppercase tracking-wider">
                                                    Reference Number
                                                </th>

                                                <th scope="col"
                                                    class="px-6 py-3 text-left text-xs font-bold text-black dark:text-gray-400 uppercase tracking-wider">
                                                    Generated By
                                                </th>
                                                <th scope="col" class="relative px-6 py-3">
                                                    <span class="sr-only">View</span>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700">
                                            <tr v-for="(record, index) in records" :key="record.record_id">
                                                <td
                                                    class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                                                    {{ record.record_id }}
                                                </td>
                                                <td
                                                    class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                    {{ record.client_name }}
                                                </td>
                                                <td
                                                    class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                    {{ record.reference_number }}
                                                </td>
                                                <td
                                                    class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                                    {{ record.user_name }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                                    <a :href="record.record_link" target="_blank"
                                                        class="text-indigo-600 hover:text-indigo-900">
                                                        View
                                                    </a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
