<template>
    <AppLayout title="Client Details">
        <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="p-6">
                    <h2 v-if="client" class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
                        {{ console.log('client', client) }}
                        {{ client.name }}'s Details
                    </h2>
                    <p v-if="client" class="mt-4">Reference Number: {{ client.reference_number }}</p>
                    <p v-if="client" class="mt-2">Total Barcodes: {{ client.total_barcodes }}</p>
                    <h3 v-if="client" class="mt-6 font-semibold text-lg">Records:</h3>
                    <div v-if="client && (!client.records || client.records.length === 0)">
                        No Records Found
                    </div>
                    <div v-if="client && client.records && client.records.length > 0">
                        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                            <thead class="bg-gray-50 dark:bg-gray-800">
                                <tr>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-bold text-black dark:text-gray-400 uppercase tracking-wider">
                                        Record Id
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-bold text-black dark:text-gray-400 uppercase tracking-wider">
                                        Generated By
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-bold text-black dark:text-gray-400 uppercase tracking-wider">
                                        Link
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700">
                                <tr v-for="(record, index) in client.records" :key="record.id">
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">
                                        {{ index + 1 }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                        {{ record.user.name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                                        <a :href="record.record_link" target="_blank"
                                            class="text-indigo-600 hover:text-indigo-900">
                                            View PDF
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>

<script setup>
import { defineProps } from 'vue';
import AppLayout from '@/Layouts/AppLayout.vue';

const props = defineProps({
    client: {
        type: Object,
        default: null,
    }
});
</script>
